#!/bin/bash

dal=$(find /scratch/u01 -name 'setDomainEnv.sh' | tail -n 1 )
val=$(cat $dal | grep "WL_HOME=" | cut -d'=' -f2 )
cal=$(cat $dal | grep "DOMAIN_HOME=" | cut -d'=' -f2 | head -n 1)
WL_HOME=$(echo "$val" | tr -d '"')
DOMAIN_HOME=$(echo "$cal" | tr -d '"')

export WL_HOME=$WL_HOME
export DOMAIN_HOME=$DOMAIN_HOME

cd $WL_HOME
cd ..
MW_HOME=$(pwd)
export MW_HOME=$MW_HOME

PATCH_TO_REMOVE="FMJJ"

cd ${MW_HOME}/utils/bsu

echo "################################################################################"
echo "Removing patch=$PATCH_TO_REMOVE"
echo "################################################################################"

sed -i 's/Xms128m/Xms1024m/g' bsu.sh
sed -i 's/Xms256m/Xms1024m/g' bsu.sh
sed -i 's/Xms512m/Xms1024m/g' bsu.sh
sed -i 's/Xmx256m/Xmx2048m/g' bsu.sh
sed -i 's/Xmx512m/Xmx2048m/g' bsu.sh
sed -i 's/Xmx1024m/Xmx2048m/g' bsu.sh

${MW_HOME}/utils/bsu/bsu.sh -remove -prod_dir=${MW_HOME}/wlserver_10.3 -patchlist=${PATCH_TO_REMOVE}

echo "Status"

./bsu.sh -view -status=applied -prod_dir=${MW_HOME}/wlserver_10.3

